---
title: "Mitocarta enrichment for upset plot results"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# External libraries
library(data.table)
#fix to install the below 2 packages on R version 4.2 can be found in the 
#blog post => https://support.bioconductor.org/p/118405/
library(org.Hs.eg.db)
library(org.Rn.eg.db)
library(MotrpacBicQC)
library(ggplot2)
library(gprofiler2)
library(MotrpacRatTraining6moData)

data_dir = "~/work/Github/motrpac-rat-training-mitochondria/data/upset_plot/"
#output_dir = "~/work/Github/motrpac-rat-training-mitochondria/results/"
output_dir="/Users/araja7/work/companion/mitochondria/scratch/output/"
```

Load existing mito annotation data (see `mito_biomarker_analysis.Rmd`):
```{r}
load("~/work/Github/motrpac-rat-training-mitochondria/data/mito_gene_annotation.RData")
# Create a feature to gene to mito mapping
mt_symbols = mt$gene_symbol
# Remove RRBS and ATAC features
FEATURE_TO_GENE = FEATURE_TO_GENE[!grepl("cluster",FEATURE_TO_GENE$feature_ID),]
FEATURE_TO_GENE = FEATURE_TO_GENE[!grepl("^chr\\d",FEATURE_TO_GENE$feature_ID,perl=T),]
gc()
FEATURE_TO_GENE$is_mito = FEATURE_TO_GENE$gene_symbol %in% mt_symbols
mito_features = FEATURE_TO_GENE$feature_ID[FEATURE_TO_GENE$is_mito]
```


```{r}
#Transcriptomics 
selected_sets = list()
selected_sets[["adrenal_bat_colon"]] = 
  fread(paste0(data_dir,"ad_bat_col_gene_symbols.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
selected_sets[["common"]] = 
  fread(paste0(data_dir,"ad_bat_col_blood_skmvl-skmgn_gene_symbols.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
selected_sets[["adrenal_bat_colon_skm-vl"]] = 
  fread(paste0(data_dir,"ad_bat_colon_skm-vl_gene_symbols.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
selected_sets[["adrenal_bat_heart"]] = 
  fread(paste0(data_dir,"ad_bat_heart_gs.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
```
```{r}
#Proteomics
selected_sets = list()
selected_sets[["skm-gn_liver_heart"]] = 
  fread(paste0(data_dir,"skm-liver-heart-prot-sig-genes.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
selected_sets[["skm-gn_heart"]] = 
  fread(paste0(data_dir,"skm-heart-port-sig-genes.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
selected_sets[["skm-gn_wat"]] = 
  fread(paste0(data_dir,"skm-wat-prot-sig-genes.txt"),
        header=F,stringsAsFactors = F,data.table = F)[,1]
```
```{r}
simple_enrichment_analysis<-function(s,univ,pathways,min_size=5,setname=""){
  s = intersect(s,univ)
  if(length(s)<min_size){
    print("Warning: input set is smaller than min_size, returning NULL")
    return(NULL)
  }
  v1 = univ %in% s
  enrichment_results = c()
  for(pname in names(pathways)){
    pg = pathways[[pname]]
    pg = intersect(pg,univ)
    if(length(pg)<min_size){next}
    v2 = univ %in% pg
    fisher_res = fisher.test(table(v1,v2),alternative = "g")
    overlap_set = intersect(s,pg)
    res = data.frame(
        setname=setname,
        pathway = pname,
        setsize = length(s),pathwaysize=length(pg),
        overlap = length(overlap_set),
        p = fisher_res$p.value,
        genes = paste(overlap_set,collapse=",")
    )
    enrichment_results = rbind(enrichment_results,res)
  }
  return(enrichment_results)
}

enrichment_results = c()
univ = mt$gene_symbol
for (setname in names(selected_sets)){
  enr_res =  simple_enrichment_analysis(
              selected_sets[[setname]],univ,
              mitocarta_pathways,setname = setname)
  if(!is.null(enr_res)){
    enrichment_results=rbind(enrichment_results,enr_res)
  }
}
enrichment_results$q = p.adjust(enrichment_results$p,method="fdr")
selected_enrichment_results = enrichment_results[enrichment_results$q < 0.1 &
  enrichment_results$overlap > 1 & enrichment_results$pathwaysize < 200,]
dim(selected_enrichment_results)

write.table(selected_enrichment_results,
            file = paste0(output_dir,"upset_sets_enrichment_results.txt"),
            sep="\t",quote=F,row.names = F)

```

```{r}
#proteomics 
write.table(selected_enrichment_results,
            file = paste0(output_dir,"upset_sets_enrichment_results_proteomics.txt"),
            sep="\t",quote=F,row.names = F)
```

