---
title: "Pro data DEA with difference of differences"
author: "David Amar"
date: "8/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# External libraries
library(data.table)
library(limma)
library(org.Hs.eg.db)
library(MotrpacBicQC)
library(plotrix)
library(metap)
library(IHW)
library(corrplot)
# Load MoTrPAC data:
library(MotrpacRatTraining6moData)

data_dir = "~/Desktop/repos/motrpac-rat-training-mitochondria/data/"
output_dir = "~/Desktop/MoTrPAC/data/pass1b_6m/"
```

# Load datasets

```{r define data set}
# get animal code data
tissue_codes = names(TISSUE_CODE_TO_ABBREV)

# Add outliers and phenotypic data
outliers = as.character(OUTLIERS[,1])
pheno = PHENO
# also add vena cava outliers
venacv_outliers = unique(pheno[
  pheno$sex=="female" & pheno$sacrificetime %in% c("1w","2w") & 
    pheno$specimen.processing.sampletypedescription=="Aorta", "viallabel"])
outliers = union(outliers, venacv_outliers)
rownames(pheno) = as.character(pheno$viallabel)
```


# Run differential analysis with DoD

## Auxlilary functions

This code was "borrowed" from the `MotrpacRatTraining6mo` R package. 

```{r}
library(dplyr)
library(tibble)
library(tidyr)
library(purrr)

# Rows in additional_covs should match columns in x
proteomics_timewise_dea_dod  = function(x,covs,assay, tissue1,tissue2){
  tpDA_split_sex = c() # keep the timewise results
  x = as.matrix(x)
  
  #Variables that save sex-specific results
  sex_res = list() #F-test result
  sex_ttest_res = list() #T-test result
  
  additional_covs = setdiff(colnames(covs),c("tr","sex","group","bid","tissue"))
  form = as.formula(paste(c("~0 + tr:tissue ",additional_covs),collapse="+"))
  
  for(SEX in c('M','F')){
    curr_meta = covs %>% filter(sex == SEX) 
    curr_counts = x[,rownames(curr_meta)]
    design = model.matrix(form,data=curr_meta)
    # limma's makeContrasts does not work with ':', change for now,
    # change back before fitting limma
    colnames(design) = gsub(":",".",colnames(design))
    
    #Set contrasts
    currContrasts = c()
    for(week in c("1","2","4","8")){
      weekC = paste0(
        "tr",week,"_0.tissue",tissue1,"-",
        "tr8_1.tissue",tissue1,"-",
        "tr",week,"_0.tissue",tissue2,"+",
        "tr8_1.tissue",tissue2
      )
      currContrasts = c(currContrasts,weekC)
    }
    currContrasts = c(currContrasts,
                      paste(currContrasts,collapse = "+"))
    cont.matrix = makeContrasts(contrasts=currContrasts, levels = design)
    colnames(cont.matrix) = c("1w","2w","4w","8w","sum")
    
    # reinstate the interaction terms
    colnames(design) = gsub("\\.",":",colnames(design))
    rownames(cont.matrix) =  gsub("\\.",":",rownames(cont.matrix) )
    
    # Fit the new model
    limma_model2 = lmFit(curr_counts,design)
    lmfit.cont <- contrasts.fit(limma_model2, cont.matrix)
    lmfit.cont.ebayes <- eBayes(lmfit.cont)
    
    #Extract results for each timepoint
    for(curr_tp in colnames(lmfit.cont.ebayes$t)){
      
      #Extract results
      limma_res = topTable(lmfit.cont.ebayes,
                           coef = curr_tp,number = Inf,sort.by = "none")
      
      curr_res = data.frame(
        feature_ID = rownames(limma_res),
        tissue1=tissue1,
        tissue2=tissue2,
        assay=assay,
        sex = if_else(SEX == "M","male","female"),
        logFC_se = limma_res$logFC/limma_res$t,
        logFC = limma_res$logFC,
        tscore = limma_res$t,
        covariates = paste(additional_covs,collapse=","),
        comparison_group = curr_tp,
        p_value = limma_res$P.Value
      )
      # Add NA counts
      if(curr_tp=="sum"){
        curr_res$numNAs = rowSums(is.na(x))
      }
      else{
        case_samps = covs %>% filter(sex == SEX &group == curr_tp) %>%rownames()
        control_samps = covs %>% filter(sex == SEX &group == "control") %>%rownames()
        curr_res$numNAs = rowSums(is.na(x[,c(case_samps,control_samps)]))
      }
      
      # Add the results
      tpDA_split_sex = rbind(tpDA_split_sex,curr_res)
    }
  }
  return(tpDA_split_sex)
}

```

## Run DiD on selected tissue pairs (and their omes)

```{r rna-seq dea table,eval=T,warning=F,results = "hide"}
DiD_dea_results = c()
omes = c("PROT","PHOSPHO")
tissue_pairs = rbind(
  c("HEART","SKMGN"),
  c("LIVER","HEART")
)
for(ome in omes){
  for(i in 1:nrow(tissue_pairs)){
    tissue1 = tissue_pairs[i,1]
    tissue2 = tissue_pairs[i,2]
    print(paste(tissue1,tissue2,ome))
    x1 = get(sprintf("%s_%s_NORM_DATA", ome,gsub("-","",tissue1))) %>%
          column_to_rownames(var = "feature_ID") 
    x1 = x1[,-c(1:3)]
    x2 = get(sprintf("%s_%s_NORM_DATA", ome,gsub("-","",tissue2))) %>%
          column_to_rownames(var = "feature_ID") 
    x2 = x2[,-c(1:3)]

    #Specify covariates
    covs1 <-  PHENO %>%
      filter(viallabel %in% colnames(x1)) %>%
      transmute(
        sex = if_else(sex == "male","M","F"),
        group,
        tr = factor(case_when(
            group == "control" ~ "8_1",
            group == "1w" ~ "1_0",
            group == "2w" ~ "2_0",
            group == "4w" ~ "4_0",
            group == "8w" ~ "8_0",),
            levels = c("8_1","1_0","2_0","4_0","8_0")
        )
      )
    covs1 <- covs1[colnames(x1),]
    covs2 <-  PHENO %>%
      filter(viallabel %in% colnames(x2)) %>%
      transmute(
        sex = if_else(sex == "male","M","F"),
        group,
        tr = factor(case_when(
            group == "control" ~ "8_1",
            group == "1w" ~ "1_0",
            group == "2w" ~ "2_0",
            group == "4w" ~ "4_0",
            group == "8w" ~ "8_0",),
            levels = c("8_1","1_0","2_0","4_0","8_0")
        )
      )
    covs2 <- covs2[colnames(x2),]
    
    # merge the datasets
    x1_vials = colnames(x1)
    x2_vials = colnames(x2)
    colnames(x1) = sapply(colnames(x1),substring,1,5)
    colnames(x2) = sapply(colnames(x2),substring,1,5)
    names(x1_vials) = colnames(x1)
    names(x2_vials) = colnames(x2)
    rownames(covs1) = colnames(x1)
    rownames(covs2) = colnames(x2)
    shared_bids = intersect(colnames(x2),colnames(x1))
    x1 = x1[,shared_bids]
    x2 = x2[,shared_bids]
    x1_vials = x1_vials[shared_bids]
    x2_vials = x2_vials[shared_bids]
    covs1 = covs1[shared_bids,]
    covs2 = covs2[shared_bids,]
    covs1$tissue = tissue1
    covs1$bid = shared_bids
    covs2$tissue = tissue2
    covs2$bid = shared_bids
    
    shared_features = intersect(rownames(x1),rownames(x2))
    x1 = x1[shared_features,]
    x2 = x2[shared_features,]
    
    x = cbind(x1,x2)
    colnames(x)  = c(x1_vials,x2_vials)
    covs = rbind(covs1,covs2)
    rownames(covs) = colnames(x)
    
    curr_DiD_results = proteomics_timewise_dea_dod(x,covs,ome, tissue1,tissue2)
    DiD_dea_results = rbind(DiD_dea_results,curr_DiD_results)
  }
}

# Use IHW for adjustment
is_sum = DiD_dea_results$comparison_group=="sum"
table(is_sum)
DiD_dea_results$ihw_q = NA
DiD_dea_results$ihw_q[is_sum] = IHW::ihw(
      DiD_dea_results$p_value[is_sum],
      factor(paste(DiD_dea_results$tissue1,DiD_dea_results$tissue2)[is_sum]),
      alph = 0.05)@df$adj_pvalue

save(DiD_dea_results,file=paste0(output_dir,"tissue_DiD_dea_prot_results.RData"))
```

## Some basic stats of the results

```{r}
load(paste0(output_dir,"tissue_DiD_dea_prot_results.RData"))
DiD_dea_results$tissues = paste(DiD_dea_results$tissue1,DiD_dea_results$tissue2,sep=",")
table(DiD_dea_results$ihw_q < 0.1,DiD_dea_results$tissues)
```

## Heart vs. muscle

```{r}
DoD_selected_sets = list()
selected_feature_inds = !is.na(DiD_dea_results$ihw_q) &
  DiD_dea_results$ihw_q < 0.1 & DiD_dea_results$tissues=="HEART,SKMGN"
selected_features = DiD_dea_results[selected_feature_inds,"feature_ID"]
DoD_selected_sets[["ALL"]] = FEATURE_TO_GENE[FEATURE_TO_GENE$feature_ID %in% selected_features,"gene_symbol"]
DoD_selected_sets[["ALL"]] = unique(DoD_selected_sets[["ALL"]][!is.na(DoD_selected_sets[["ALL"]])])

```

Clustering analysis:

```{r}
# Get the z-scores and FCs for the contrasts
get_zmat<-function(timewise,timewise_col=NULL){
  if(is.null(timewise_col)){
    timewise_col = "zscore"
  }
  if(!timewise_col %in% colnames(timewise)){
    timewise_col = "tscore"
  }
  rs = unique(timewise$feature_ID)
  cs = c(
    paste("female",sort(unique(timewise$comparison_group)),sep=","),
    paste("male",sort(unique(timewise$comparison_group)),sep=",")
  )
  m = matrix(NA,nrow=length(rs),ncol=length(cs),dimnames = list(rs,cs))
  for(col in cs){
    arr = strsplit(col,split=",")[[1]]
    tmp = timewise[
      timewise$sex == arr[1] & timewise$comparison_group == arr[2],
    ]
    m[tmp$feature_ID,col] = tmp[[timewise_col]] 
  }
  return(m)
}

is_curr_tissues = DiD_dea_results$tissues == "HEART,SKMGN"
is_in_ihw_results = DiD_dea_results$feature_ID %in% selected_features
heart_vs_muscle_tscores = get_zmat(
  DiD_dea_results[is_curr_tissues & is_in_ihw_results,]
)
heart_vs_muscle_tscores = heart_vs_muscle_tscores[,!grepl(",sum",colnames(heart_vs_muscle_tscores))]
k_res = list()
set.seed(123)
for(k in 1:20){
  k_res[[k]] = kmeans(heart_vs_muscle_tscores,k,nstart = 50,iter.max = 500)
}
within_rss = sapply(k_res,function(x)sum(x$withinss))
plot(within_rss,type="b",ylab = "Within cluster SS",xlab="Number of clusters",col="blue")
cluster_obj = k_res[[4]]$cluster
table(cluster_obj)
for(cl in unique(cluster_obj)){
  cl_features = names(cluster_obj)[cluster_obj==cl]
  cl_genes = FEATURE_TO_GENE[FEATURE_TO_GENE$feature_ID %in% cl_features,"gene_symbol"]
  cl_genes = unique(cl_genes[!is.na(cl_genes)])
  DoD_selected_sets[[as.character(cl)]] = cl_genes
}

```

Plot the clusters:

```{r}
library(gplots)
for(cl in unique(cluster_obj)){
  cl_features = names(cluster_obj)[cluster_obj==cl]
  cl_m = heart_vs_muscle_tscores[cl_features,]
  heatmap.2(cl_m,scale = "none",trace="none",col=bluered)
}

```

## Enrichment analysis

```{r}
library(gprofiler2)
bg = unique(DiD_dea_results[DiD_dea_results$tissues=="HEART,SKMGN","feature_ID"])
bg_genes = FEATURE_TO_GENE[FEATURE_TO_GENE$feature_ID %in% bg,"gene_symbol"]
bg_genes = unique(bg_genes[!is.na(bg_genes)])
res = gost(DoD_selected_sets,
    organism='rnorvegicus',
    significant=FALSE, # return all results
    correction_method='fdr', # it will not return unadjusted p-values. 
    sources=c('KEGG','REAC'),
    custom_bg=bg_genes,
    domain_scope='custom',
    evcodes=T)
res$result$q = p.adjust(res$result$p_value,method="fdr")
res$selected_results = res$result[res$result$q < 0.1,]
dim(res$selected_results)
res$selected_results
```



