---
title: "Mito-adjusted prot data DEA"
author: "David Amar"
date: "6/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# External libraries
library(data.table)
library(limma)
library(org.Hs.eg.db)
library(MotrpacBicQC)
library(plotrix)
library(metap)
library(IHW)
library(corrplot)
# Load MoTrPAC data:
library(MotrpacRatTraining6moData)

data_dir = "~/Desktop/repos/motrpac-rat-training-mitochondria/data/"
output_dir = "~/Desktop/MoTrPAC/data/pass1b_6m/"
```

# Load datasets

```{r define data set}
# get animal code data
tissue_codes = names(TISSUE_CODE_TO_ABBREV)

# Add outliers and phenotypic data
outliers = as.character(OUTLIERS[,1])
pheno = PHENO
# also add vena cava outliers
venacv_outliers = unique(pheno[
  pheno$sex=="female" & pheno$sacrificetime %in% c("1w","2w") & 
    pheno$specimen.processing.sampletypedescription=="Aorta", "viallabel"])
outliers = union(outliers, venacv_outliers)
rownames(pheno) = as.character(pheno$viallabel)
```

Load mito biomarker data (see `mito_biomarker_analysis.Rmd`)
```{r}
load(paste0(data_dir,"mt_biomarkers.RData"))
```

Load existing mito annotation data (see `mito_biomarker_analysis.Rmd`):
```{r}
load(paste0(data_dir,"mito_gene_annotation.RData"))
```

# Run differential analysis

## Auxlilary functions

This code was "borrowed" from the `MotrpacRatTraining6mo` R package. 

```{r}
library(dplyr)
library(tibble)
library(tidyr)
library(purrr)

# Rows in additional_covs should match columns in x
proteomics_timewise_dea  = function(x,covs,assay, tissue){
  tpDA_split_sex = c() # keep the timewise results
  x = as.matrix(x)
  
  #Variables that save sex-specific results
  sex_res = list() #F-test result
  sex_ttest_res = list() #T-test result
  
  formula_covs = setdiff(colnames(covs),c("sex","group"))
  form = as.formula(paste(c("~0",formula_covs),collapse="+"))
  
  for(SEX in c('M','F')){
    curr_meta = covs %>% filter(sex == SEX) 
    curr_counts = x[,rownames(curr_meta)]
    
    #Extract treatment covariate
    tr <- curr_meta$tr
    design = model.matrix(form,data=curr_meta)
    
    #Set contrasts
    cont.matrix = makeContrasts(
      tr1_0 - tr8_1, tr2_0 - tr8_1, tr4_0 - tr8_1, tr8_0 - tr8_1, 
      levels = design
    )
    colnames(cont.matrix) = c("1w","2w","4w","8w")
    
    # Fit the new model
    limma_model2 = lmFit(curr_counts,design)
    lmfit.cont <- contrasts.fit(limma_model2, cont.matrix)
    lmfit.cont.ebayes <- eBayes(lmfit.cont)
    
    #Extract results for each timepoint
    for(curr_tp in colnames(lmfit.cont.ebayes$t)){
      
      #Extract results
      limma_res = topTable(lmfit.cont.ebayes,
                           coef = curr_tp,number = Inf,sort.by = "none")
      
      curr_res = data.frame(
        feature_ID = rownames(limma_res),
        tissue=tissue,
        assay=assay,
        sex = if_else(SEX == "M","male","female"),
        logFC_se = limma_res$logFC/limma_res$t,
        logFC = limma_res$logFC,
        tscore = limma_res$t,
        covariates = paste(formula_covs,collapse=","),
        comparison_group = curr_tp,
        p_value = limma_res$P.Value
      )
      # Add group average intensities
      case_samps = covs %>% 
        filter(sex == SEX &
                 group == curr_tp) %>%
        rownames()
      curr_res$comparison_average_intensity = apply(x[,case_samps],1,mean,na.rm=TRUE)
      
      control_samps = covs %>% 
        filter(sex == SEX &
                 group == "control") %>%
        rownames()
      curr_res$reference_average_intensity =
        apply(x[,control_samps],1,mean,na.rm=TRUE)
      
      # Add NA counts
      curr_res$numNAs = rowSums(is.na(x[,c(case_samps,control_samps)]))
      
      # Add the results
      tpDA_split_sex = rbind(tpDA_split_sex,curr_res)
    }
  }
  return(tpDA_split_sex)
}

proteomics_training_dea  <- function(x,covs,assay, tissue){
  x = as.matrix(x)
  ftest_res_split_sex = c() # keeps all ftest results
  #Variables that save sex-specific results
  sex_res = list() #F-test result
  sex_ttest_res = list() #T-test result
  
  formula_covs = setdiff(colnames(covs),c("sex","group"))
  form = as.formula(paste(c("~1",formula_covs),collapse="+"))
  
  for(SEX in c('M','F')){
    curr_meta = covs %>% filter(sex == SEX) 
    curr_counts = x[,rownames(curr_meta)]
    
    # F-test analysis - training-dea table
    #Extract treatment covariate
    tr <- curr_meta$tr
    #Generate the experimental model
    design <- model.matrix(form,data=curr_meta)
    fit <- lmFit(curr_counts, design)
    fit.eb <- eBayes(fit)
    
    #Extract results
    res = topTable(fit.eb, coef = 2:5, n=nrow(fit.eb))
    dt = data.table(tissue=tissue,
        assay=assay,
        feature_ID=rownames(res),
        fscore=res$`F`,
        p_value = res$P.Value,
        full_model = paste(c("~1",gsub("tr","group",formula_covs)),collapse="+"),
        reduced_model = paste(c("~1",gsub("tr","",formula_covs)),collapse="+"))
    sex_res[[SEX]] = dt
  }
  
  #Merge F-test results
  merged = data.frame(merge(sex_res[['M']], sex_res[['F']], 
                            by=c("tissue","assay","feature_ID","full_model","reduced_model"), 
                            suffixes=c('_male','_female'))) %>%
    mutate(p_value_male = replace_na(p_value_male,1),
           p_value_female = replace_na(p_value_female,1)) %>%
    mutate(p_value = map2_dbl(p_value_male,p_value_female,
                              function(x,y){sumlog(c(x,y))$p}))
  
  ftest_res_split_sex <- rbind(ftest_res_split_sex,merged)
  return(ftest_res_split_sex)
}

```

## Adjust for mtDNA levels

```{r rna-seq dea table,eval=T,warning=F,results = "hide"}
dea_results = list()
omes = c("PROT","PHOSPHO")
tissues = c("CORTEX","HEART","KIDNEY","LIVER","LUNG","SKMGN","WATSC")
for(ome in omes){
  dea_results[[ome]] = list()
  for(tissue in tissues){
    print(paste(tissue,ome))
    x = get(sprintf("%s_%s_NORM_DATA", ome,gsub("-","",tissue))) %>%
          column_to_rownames(var = "feature_ID") 
    x = x[,-c(1:3)]
    x_bid = sapply(colnames(x),substring,1,5)
    additional_covs = mt_biomarkers[[tissue]]
    rownames(additional_covs) = as.character(additional_covs$bid)
      
    shared_bids = intersect(x_bid,additional_covs$bid)
    x = x[,names(x_bid[x_bid %in% shared_bids])]
    x_bid = sapply(colnames(x),substring,1,5)
    additional_covs = additional_covs[x_bid,c("mt_reads","clPC1","clPC2","clPC3")]
    rownames(additional_covs) = names(x_bid)
    selected_mt_markers = colSums(is.na(additional_covs))==0
    mt_cov_names = colnames(additional_covs)[selected_mt_markers]
    additional_covs = additional_covs[selected_mt_markers]
      
    #Specify covariates
    covs <-  PHENO %>%
      filter(viallabel %in% colnames(x)) %>%
      transmute(
        sex = if_else(sex == "male","M","F"),
        group,
        tr = factor(case_when(
            group == "control" ~ "8_1",
            group == "1w" ~ "1_0",
            group == "2w" ~ "2_0",
            group == "4w" ~ "4_0",
            group == "8w" ~ "8_0",),
            levels = c("8_1","1_0","2_0","4_0","8_0")
        )
      )
    covs <- covs[colnames(x),]
    if(!is.null(additional_covs)){
      covs = cbind(covs,additional_covs)
    }
      
    timewise_dea = proteomics_timewise_dea(x,covs[,c(1:3)],ome,tissue)
    timewise_dea_mt_adjusted = proteomics_timewise_dea(x,covs,ome,tissue)
    training_dea = proteomics_training_dea(x,covs[,c(1:3)],ome,tissue)
    training_dea_mt_adjusted = proteomics_training_dea(x,covs,ome,tissue)
      
    dea_results[[ome]][[tissue]] = list(
        mt_cov_names = mt_cov_names,
        timewise_dea = timewise_dea,
        timewise_dea_mt_adjusted = timewise_dea_mt_adjusted,
        training_dea = training_dea,
        training_dea_mt_adjusted = training_dea_mt_adjusted
      )
  }
}

# Sanity check, compare our code to pre-computed DEA
for(ome in omes){
  for(tissue in tissues){
    # load data 
    da_name = paste(ome,gsub("-","",tissue),"DA",sep="_")
    curr_da = get(da_name)
    computed_da = dea_results[[ome]][[tissue]]$timewise_dea
    computed_da = as.data.frame(computed_da)
    rownames(computed_da) = paste(
      computed_da$feature_ID,computed_da$sex,computed_da$comparison_group,sep=";"
    )
    rownames(curr_da) = paste(
      curr_da$feature_ID,curr_da$sex,curr_da$comparison_group,sep=";"
    )
    rowname_jacc = length(intersect(rownames(curr_da),rownames(computed_da))) / 
      length(union(rownames(curr_da),rownames(computed_da)))
    if(rowname_jacc < 1){
      print(paste("In tissue",tissue,"covered timeise data differs"))
    }
    curr_da = curr_da[rownames(computed_da),]
    inds = !is.na(curr_da$p_value) & !is.na(computed_da$p_value)
    rho1 = round(cor(curr_da$p_value[inds],computed_da$p_value[inds]),digits = 4)
    rho2 = round(cor(curr_da$logFC[inds],computed_da$logFC[inds]),digits = 4)
    print(paste(tissue,ome,rho1,rho2))
  }
}

save(dea_results,file=paste0(output_dir,"mito_paper_dea_prot_results.RData"))
```

Add FDR adjustment using IHW per ome

```{r}
# Merge tables and use IHW in each ome
dea_combined = list()
for(ome in names(dea_results)){
  dea_combined[[ome]] = list()
  for(j in 1:length(dea_results[[ome]])){
    print(j)
    tissue = names(dea_results[[ome]])[j]
    for(nn in names(dea_results[[ome]][[j]])){
      d = dea_results[[ome]][[j]][[nn]]
      d = as.data.frame(d)
      d$tissue_abbr = tissue
      if(!is.null(dea_combined[[ome]][[nn]])){
        missing_cols = setdiff(colnames(dea_combined[[ome]][[nn]]),colnames(d))
        for(cc in missing_cols){d[[cc]]=NA}
          d = d[,colnames(dea_combined[[ome]][[nn]])]
        }
      dea_combined[[ome]][[nn]] = rbind(dea_combined[[ome]][[nn]],d)
    }
  }
}

sapply(dea_combined,function(y)sapply(y,nrow))
for(ome in names(dea_results)){
  dea_combined[[ome]]$training_dea$ihw_q = IHW::ihw(
      dea_combined[[ome]]$training_dea$p_value,
      factor(dea_combined[[ome]]$training_dea$tissue_abbr),
      alph = 0.05)@df$adj_pvalue
  dea_combined[[ome]]$training_dea_mt_adjusted$ihw_q = IHW::ihw(
      dea_combined[[ome]]$training_dea_mt_adjusted$p_value,
      factor(dea_combined[[ome]]$training_dea_mt_adjusted$tissue_abbr),
      alph = 0.05)@df$adj_pvalue
  print(table(dea_combined[[ome]]$training_dea$ihw_q < 0.05,
      dea_combined[[ome]]$training_dea_mt_adjusted$ihw_q < 0.05))
}

save(dea_combined,
     file=paste0(output_dir,"ihw_adjusted_mito_paper_dea_prot_results.RData"))
```


```{r}
load(paste0(output_dir,"ihw_adjusted_mito_paper_dea_prot_results.RData"))
```






